# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: streamlit-pypsa
channels:
  - conda-forge
  - bioconda
  - gurobi
dependencies:
  - numpy
  - pandas
  - pre-commit
  - streamlit
  - plotly
  - pypsa
